[2023-01-27T04:59:01.818+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: fhv_taxi_data_dag_v1.transform_csv_to_parquet scheduled__2021-07-01T00:00:00+00:00 [queued]>
[2023-01-27T04:59:01.839+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: fhv_taxi_data_dag_v1.transform_csv_to_parquet scheduled__2021-07-01T00:00:00+00:00 [queued]>
[2023-01-27T04:59:01.840+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-01-27T04:59:01.840+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-01-27T04:59:01.840+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-01-27T04:59:01.877+0000] {taskinstance.py:1300} INFO - Executing <Task(_PythonDecoratedOperator): transform_csv_to_parquet> on 2021-07-01 00:00:00+00:00
[2023-01-27T04:59:01.894+0000] {standard_task_runner.py:55} INFO - Started process 7900 to run task
[2023-01-27T04:59:01.900+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'fhv_taxi_data_dag_v1', 'transform_csv_to_parquet', 'scheduled__2021-07-01T00:00:00+00:00', '--job-id', '5810', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag_v1_fhv.py', '--cfg-path', '/tmp/tmpzi32pj49']
[2023-01-27T04:59:01.904+0000] {standard_task_runner.py:83} INFO - Job 5810: Subtask transform_csv_to_parquet
[2023-01-27T04:59:02.064+0000] {task_command.py:388} INFO - Running <TaskInstance: fhv_taxi_data_dag_v1.transform_csv_to_parquet scheduled__2021-07-01T00:00:00+00:00 [running]> on host 8bc22b99c76b
[2023-01-27T04:59:02.280+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=fhv_taxi_data_dag_v1
AIRFLOW_CTX_TASK_ID=transform_csv_to_parquet
AIRFLOW_CTX_EXECUTION_DATE=2021-07-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-07-01T00:00:00+00:00
[2023-01-27T04:59:02.283+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/operators/python.py:192: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version.


  return self.python_callable(*self.op_args, **self.op_kwargs)

[2023-01-27T04:59:05.835+0000] {logging_mixin.py:137} INFO - fhv_tripdata_2021-07.parquet
[2023-01-27T04:59:05.899+0000] {python.py:177} INFO - Done. Returned value was: fhv_tripdata_2021-07.parquet
[2023-01-27T04:59:05.955+0000] {taskinstance.py:1323} INFO - Marking task as SUCCESS. dag_id=fhv_taxi_data_dag_v1, task_id=transform_csv_to_parquet, execution_date=20210701T000000, start_date=20230127T045901, end_date=20230127T045905
[2023-01-27T04:59:06.040+0000] {local_task_job.py:208} INFO - Task exited with return code 0
[2023-01-27T04:59:06.102+0000] {taskinstance.py:2578} INFO - 1 downstream tasks scheduled from follow-on schedule check
