[2023-01-27T04:57:34.904+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: fhv_taxi_data_dag_v1.transform_csv_to_parquet scheduled__2020-04-01T00:00:00+00:00 [queued]>
[2023-01-27T04:57:34.922+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: fhv_taxi_data_dag_v1.transform_csv_to_parquet scheduled__2020-04-01T00:00:00+00:00 [queued]>
[2023-01-27T04:57:34.922+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-01-27T04:57:34.922+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-01-27T04:57:34.922+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-01-27T04:57:34.945+0000] {taskinstance.py:1300} INFO - Executing <Task(_PythonDecoratedOperator): transform_csv_to_parquet> on 2020-04-01 00:00:00+00:00
[2023-01-27T04:57:34.957+0000] {standard_task_runner.py:55} INFO - Started process 6892 to run task
[2023-01-27T04:57:34.961+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'fhv_taxi_data_dag_v1', 'transform_csv_to_parquet', 'scheduled__2020-04-01T00:00:00+00:00', '--job-id', '5723', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag_v1_fhv.py', '--cfg-path', '/tmp/tmpbjugm2wb']
[2023-01-27T04:57:34.964+0000] {standard_task_runner.py:83} INFO - Job 5723: Subtask transform_csv_to_parquet
[2023-01-27T04:57:35.065+0000] {task_command.py:388} INFO - Running <TaskInstance: fhv_taxi_data_dag_v1.transform_csv_to_parquet scheduled__2020-04-01T00:00:00+00:00 [running]> on host 8bc22b99c76b
[2023-01-27T04:57:35.208+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=fhv_taxi_data_dag_v1
AIRFLOW_CTX_TASK_ID=transform_csv_to_parquet
AIRFLOW_CTX_EXECUTION_DATE=2020-04-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-04-01T00:00:00+00:00
[2023-01-27T04:57:35.212+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/operators/python.py:192: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version.


  return self.python_callable(*self.op_args, **self.op_kwargs)

[2023-01-27T04:57:36.990+0000] {logging_mixin.py:137} INFO - fhv_tripdata_2020-04.parquet
[2023-01-27T04:57:37.024+0000] {python.py:177} INFO - Done. Returned value was: fhv_tripdata_2020-04.parquet
[2023-01-27T04:57:37.052+0000] {taskinstance.py:1323} INFO - Marking task as SUCCESS. dag_id=fhv_taxi_data_dag_v1, task_id=transform_csv_to_parquet, execution_date=20200401T000000, start_date=20230127T045734, end_date=20230127T045737
[2023-01-27T04:57:37.106+0000] {local_task_job.py:208} INFO - Task exited with return code 0
[2023-01-27T04:57:37.178+0000] {taskinstance.py:2578} INFO - 1 downstream tasks scheduled from follow-on schedule check
